version: "2.3"

services:
  mongodb:
    container_name: mongo
    hostname: mongodb
    image: mongo:4.0.13
    ports:
      - "27017:27017"
    networks:
      - app

networks:
  app:
    driver: bridge
