name: Create Release PR

on: workflow_dispatch

jobs:
  # This workflow contains a single job called "greet"
  create-release-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Variables
        run: |
          echo "DATE=$(date +'%Y/%m/%d')" >> "$GITHUB_ENV"
          TARGET_BRANCH=""
          TITLE=""

          BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)
          if [[ $BRANCH == "staging" ]]; then
            TARGET_BRANCH=main
            TITLE=Production
          else
            print "Unexpected source branch for release"
            exit 0
          fi

          PRS=$(git tag -l --no-merged origin/$TARGET_BRANCH | grep -o "[0-9]\+")

          GITHUB_LINKS="<ul>"
          AUTHORS=""
          SLACK_MESSAGE=""

          gen_section() {
            echo "{\
              \"type\": \"mrkdwn\",\
              \"text\": \"<$3| *$1*>\n *Author*: $2\"\
            },"
          }

          CHANGE_COUNT=0

          for pr_number in $PRS
          do
            url=https://api.github.com/repos/vidocco/nerdtrivial/pulls/$pr_number
            link_url=https://github.com/vidocco/nerdtrivial/pull/$pr_number
            res=$(curl $url -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}')
            owner=$(echo $res | jq --raw-output '.user.login')
            pr_title=$(echo $res | jq --raw-output '.title')

            AUTHORS="$AUTHORS$owner\n"
            SLACK_MESSAGE="$SLACK_MESSAGE$(if [[ $CHANGE_COUNT -ge 10 ]];then echo $(gen_section "$pr_title" "$owner" "$link_url");fi)"
            GITHUB_LINKS="$GITHUB_LINKS<li>vidocco/nerdtrivial/pull/$pr_number</li>"
            CHANGE_COUNT=$(($CHANGE_COUNT+1))
          done

          GITHUB_LINKS="$GITHUB_LINKS</ul>"
          AUTHORS=$(echo -e $AUTHORS | sort --unique | sed -z "s/\n/,/g")
          SLACK_MESSAGE=$(echo $SLACK_MESSAGE | sed 's/.$//')

          echo "LINKS=$GITHUB_LINKS" >> "$GITHUB_ENV"
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> "$GITHUB_ENV"
          echo "TITLE=$TITLE" >> "$GITHUB_ENV"
          echo "AUTHORS=$AUTHORS" >> "$GITHUB_ENV"
          echo "SLACK_MESSAGE=$SLACK_MESSAGE" >> "$GITHUB_ENV"
          echo "CHANGE_COUNT=$CHANGE_COUNT" >> "$GITHUB_ENV"
      - uses: repo-sync/pull-request@v2
        id: open-release-pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "${{ env.TARGET_BRANCH }}"
          pr_title: "${{ env.TITLE }} Release - ${{env.DATE}}"
          pr_reviewer: "${{ env.AUTHORS }}"
          pr_body: |
            ## Changelist <br/>
            ${{ env.LINKS }}

            ## Checklist <br/>
            - [ ] All backup tasks have been performed.
      - name: Build Full Slack Message
        env:
          SLACK_MESSAGE: ${{env.SLACK_MESSAGE}}
          CHANGE_COUNT: ${{env.CHANGE_COUNT}}
          PR_URL: ${{steps.open-release-pr.outputs.pr_url}}
        run: |
          SLACK_MESSAGE_START="\
            \"blocks\": [\
              {\
                \"type\": \"section\",\
                \"text\": {\
                  \"type\": \"mrkdwn\",\
                  \"text\": \"A new backend *$TITLE release* has been created\"\
                },\
                \"accessory\": {\
                  \"type\": \"button\",\
                  \"text\": {\
                      \"type\": \"plain_text\",\
                      \"text\": \"See The Full PR\",\
                      \"emoji\": true\
                  },\
                  \"url\": \"$PR_URL\"\
                }\
              },\
              {\
                \"type\": \"header\",\
                \"text\": {\
                  \"type\": \"plain_text\",\
                  \"text\": \"Changelist\"\
                }\
              },\
              {\
                  \"type\": \"section\",\
                  \"fields\": ["

          SLACK_MESSAGE_END="]}]}"

          if [[ $CHANGE_COUNT > 10 ]]; then
            SLACK_MESSAGE_END="]\
                },\
                {\
                    \"type\": \"context\",\
                    \"elements\": [\
                        {\
                            \"type\": \"mrkdwn\",\
                            \"text\": \":rocket: and *$(($CHANGE_COUNT-10))* other changes (see PR for full details).\"\
                        }\
                    ]\
                }\
              ]"
          fi

          FULL_SLACK_MESSAGE="$SLACK_MESSAGE_START$SLACK_MESSAGE$SLACK_MESSAGE_END"
          echo "FULL_SLACK_MESSAGE=$FULL_SLACK_MESSAGE" >> "$GITHUB_ENV"
      - name: Notify support-general
        if: ${{ env.TARGET_BRANCH == 'main' }}
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
            -H "Content-type: application/json; charset=utf-8" \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -d '{ "channel": "C9ZH84S3S", ${{env.FULL_SLACK_MESSAGE}} }'
